apiVersion: v1 
kind: Pod
metadata: 
 name: my-pod
 lables: my-app
spec:
 containers: 
  - name: my-pod-container
    image: nginx
    ports: 
     - name: http
       containerPort: 80
       protocol: TCP
  - name: my-another-container
    image: tomcat
    ports:
     - name: java
    containerPort: 8080
    protocol: TCP 
