apiVersion: v1
kind: Service
metadata:
  name: my-pod
spec:
 type: NodePort
 selector:
  app: my-app
  ports:
  - protocol: TCP
      port: 80
      targetPort: 80
  - protocol: TCP
      port: 8080
      targetPort: 8080